# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70df6e5f71cbdef0688150f5ad85a82baaa7780b88190934b3c3816b4b3c222de4fe3026d953f9d2c138111c83c85c99f5bd849bb6f0285d014b130f676004de

test:
  secret_key_base: 12091a2e14556c1c2e0f8021f623e5f6c28649149a214430f0ee15fee33a6b5859db21eebcbe1fc38af1945a11e9880f41ea96e0723b156296a21159ae3d6c02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
